AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/EvalWithLocation:
  Exclude:
    - spec/**/*.rb

Style/AccessModifierDeclarations:
  Exclude:
    - spec/**/*.rb

Security/Eval:
  Exclude:
    - spec/**/*.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: never
